'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tienda
    Public Property IdRegistro As Integer
    Public Property NombreTienda As String
    Public Property NombreEmpleado As String
    Public Property Telefono As Nullable(Of Integer)
    Public Property Direccion As String
    Public Property FechaTrabajo As String

End Class
